#!/bin/sh

[ -d /opt/polkabtc ] || mkdir /opt/polkabtc
[ -d /opt/polkabtc/relayer ] || mkdir /opt/polkabtc/relayer
cp ./staked-relayer /opt/polkabtc/relayer/
cp ./keyfile.json /opt/polkabtc/relayer/
[ -d /usr/lib/systemd/system/ ] || mkdir /usr/lib/systemd/system/
cp polkabtc-relayer.service /usr/lib/systemd/system/
