#!/bin/sh
create_runner_service() {
  echo "Creating $network Runner"
  [ -d /opt/$network ] || mkdir /opt/$network
  [ -d /opt/$network/runner ] || mkdir /opt/$network/runner
  cp ./runner /opt/$network/runner/
  cp ./keyfile.json /opt/$network/runner/
  [ -d /usr/lib/systemd/system/ ] || mkdir /usr/lib/systemd/system/
  cp $network-runner.service /usr/lib/systemd/system/
}

case $1 in

  testnet)
    network="testnet"
    create_runner_service
    ;;

  testnet-interlay)
    network="testnet-interlay"
    create_runner_service
    ;;

  kintsugi)
    network="kintsugi"
    create_runner_service
    ;;

  interlay)
    network="interlay"
    create_runner_service
    ;;

  *)
    echo "Please specify a network. Valid options are: testnet, testnet-interlay, kintsugi, and interlay."
    ;;

esac
