#!/bin/sh

[ -d /opt/polkabtc ] || mkdir /opt/polkabtc
[ -d /opt/polkabtc/vault ] || mkdir /opt/polkabtc/vault
cp ./vault /opt/polkabtc/vault/
cp ./keyfile.json /opt/polkabtc/vault/
[ -d /usr/lib/systemd/system/ ] || mkdir /usr/lib/systemd/system/
cp polkabtc-vault.service /usr/lib/systemd/system/
