#!/bin/sh
create_vault_service() {
  echo "Creating $network Vault"
  [ -d /opt/$network ] || mkdir /opt/$network
  [ -d /opt/$network/vault ] || mkdir /opt/$network/vault
  cp ./vault /opt/$network/vault/
  cp ./keyfile.json /opt/$network/vault/
  [ -d /usr/lib/systemd/system/ ] || mkdir /usr/lib/systemd/system/
  cp $network-vault.service /usr/lib/systemd/system/
}

case $1 in

  testnet-kintsugi)
    network="testnet-kintsugi"
    create_vault_service
    ;;

  testnet-interlay)
    network="testnet-interlay"
    create_vault_service
    ;;

  kintsugi)
    network="kintsugi"
    create_vault_service
    ;;

  interlay)
    network="interlay"
    create_vault_service
    ;;

  *)
    echo "Please specify a network. Valid options are: testnet-kintsugi, testnet-interlay, kintsugi, and interlay."
    ;;

esac
